version: "3.8"
services:
  product-service:
    build: .
    restart: always
    depends_on:
      - mongo_product_db
    networks:
      default:
        aliases:
          - rmqnet
  mongo_product_db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    networks:
      default:
        aliases:
          - rmqnet

networks:
  default:
    name: rmqnet