version: "3.7"
services:
  product-service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_product_db
  mongo_product_db:
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017