apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-product-db
  name: mongo-product-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-product-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/rmqnet: "true"
        io.kompose.service: mongo-product-db
    spec:
      containers:
        - image: mongo:latest
          name: mongo-product-db
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
